name: CI for Github

# Set up 'triggers'?
on:
  # - Handling commits: Husky and our precommits will handle any pre-commit logic.
  # - Handling pushes: Then github actions will take care of any pushes or whatnot.

  push:
    branches:
      - main
      - feature/*
# If triggers are set off, run 'jobs'. If all jobs pass without issue, then authorize the action
jobs:
  # A 'job' that runs our application's tests.
  test:
    # Setup the OS that is going to be used
    runs-on: ubuntu-latest
    # Create the steps for this job
    steps:
      # - name: myStepName
      # - uses: some_link_to_the_step?
      # This pulls your repository code, allowing the subsequent steps to access it.
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Installs the necessary version of NodeJS, so Node Version 16.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      # Steps for installing dependencies
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
